ALTAIR_FORK_SLOT: 18446744073709551615
ALTAIR_FORK_VERSION: 0x01000000
BASE_REWARD_FACTOR: 64
BLS_WITHDRAWAL_PREFIX: 0x00
CHURN_LIMIT_QUOTIENT: 65536
DEPOSIT_CHAIN_ID: 1
DEPOSIT_CONTRACT_ADDRESS: 0x00000000219ab540356cbb839cbe05303d7705fa
DEPOSIT_NETWORK_ID: 1
DOMAIN_AGGREGATE_AND_PROOF: 0x06000000
DOMAIN_BEACON_ATTESTER: 0x01000000
DOMAIN_BEACON_PROPOSER: 0x00000000
DOMAIN_CONTRIBUTION_AND_PROOF: 0x09000000
DOMAIN_DEPOSIT: 0x03000000
DOMAIN_RANDAO: 0x02000000
DOMAIN_SELECTION_PROOF: 0x05000000
DOMAIN_SYNC_COMMITTEE: 0x07000000
DOMAIN_SYNC_COMMITTEE_SELECTION_PROOF: 0x08000000
DOMAIN_VOLUNTARY_EXIT: 0x04000000
EFFECTIVE_BALANCE_INCREMENT: 1000000000
EJECTION_BALANCE: 16000000000
EPOCHS_PER_ETH1_VOTING_PERIOD: 64
EPOCHS_PER_HISTORICAL_VECTOR: 65536
EPOCHS_PER_RANDOM_SUBNET_SUBSCRIPTION: 256
EPOCHS_PER_SLASHINGS_VECTOR: 8192
EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 256
ETH1_FOLLOW_DISTANCE: 2048
GENESIS_DELAY: 604800
GENESIS_FORK_VERSION: 0x00000000
HISTORICAL_ROOTS_LIMIT: 16777216
HYSTERESIS_DOWNWARD_MULTIPLIER: 1
HYSTERESIS_QUOTIENT: 4
HYSTERESIS_UPWARD_MULTIPLIER: 5
INACTIVITY_PENALTY_QUOTIENT: 67108864
INACTIVITY_PENALTY_QUOTIENT_ALTAIR: 50331648
INACTIVITY_SCORE_BIAS: 4
LIGHT_CLIENT_UPDATE_TIMEOUT: 8192
MAX_ATTESTATIONS: 128
MAX_ATTESTER_SLASHINGS: 2
MAX_COMMITTEES_PER_SLOT: 64
MAX_DEPOSITS: 16
MAX_EFFECTIVE_BALANCE: 32000000000
MAX_PROPOSER_SLASHINGS: 16
MAX_SEED_LOOKAHEAD: 4
MAX_VALIDATORS_PER_COMMITTEE: 2048
MAX_VALID_LIGHT_CLIENT_UPDATES: 8192
MAX_VOLUNTARY_EXITS: 16
MIN_ATTESTATION_INCLUSION_DELAY: 1
MIN_DEPOSIT_AMOUNT: 1000000000
MIN_EPOCHS_TO_INACTIVITY_PENALTY: 4
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 16384
MIN_GENESIS_TIME: 1606824000
MIN_PER_EPOCH_CHURN_LIMIT: 4
MIN_SEED_LOOKAHEAD: 1
MIN_SLASHING_PENALTY_QUOTIENT: 128
MIN_SLASHING_PENALTY_QUOTIENT_ALTAIR: 64
MIN_SYNC_COMMITTEE_PARTICIPANTS: 1
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
PROPORTIONAL_SLASHING_MULTIPLIER: 1
PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR: 2
PROPOSER_REWARD_QUOTIENT: 8
RANDOM_SUBNETS_PER_VALIDATOR: 1
SAFE_SLOTS_TO_UPDATE_JUSTIFIED: 8
SECONDS_PER_ETH1_BLOCK: 14
SECONDS_PER_SLOT: 12
SHARD_COMMITTEE_PERIOD: 256
SHUFFLE_ROUND_COUNT: 90
SLOTS_PER_EPOCH: 32
SLOTS_PER_HISTORICAL_ROOT: 8192
SYNC_COMMITTEE_SIZE: 1024
SYNC_PUBKEYS_PER_AGGREGATE: 64
TARGET_AGGREGATORS_PER_COMMITTEE: 16
TARGET_AGGREGATORS_PER_SYNC_SUBCOMMITTEE: 4
TARGET_COMMITTEE_SIZE: 128
VALIDATOR_REGISTRY_LIMIT: 1099511627776
WHISTLEBLOWER_REWARD_QUOTIENT: 512
