# Mainnet preset - lightclient patch

CONFIG_NAME: "mainnet"

# Misc
# ---------------------------------------------------------------
# 2**10 (=1,024)
SYNC_COMMITTEE_SIZE: 1024
# 2**6 (=64)
SYNC_SUBCOMMITTEE_SIZE: 64


# Time parameters
# ---------------------------------------------------------------
# 2**8 (= 256)
EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 256
# 2**6 (= 64)
EPOCHS_PER_ACTIVATION_EXIT_PERIOD: 64


# Signature domains
# ---------------------------------------------------------------
DOMAIN_SYNC_COMMITTEE: 0x07000000
