# Mainnet preset - lightclient patch

CONFIG_NAME: "minimal"

# ---------------------------------------------------------------

# 2**10 (=1,024)
SYNC_COMMITTEE_SIZE: 1024
# 2**6 (=64)
SYNC_COMMITTEE_PUBKEY_AGGREGATES_SIZE: 64
